### PR TITLE
Saagar/empty inventory

### PR DESCRIPTION
**Pull request by Saagar3690**
Placeholder for Empty Inventory

I wasn't really sure about the design and was hard to find a decent gif. I put the two best looking ones in my opinion down below. Let me know what you think and if there's any changes cosmetically you want me to make.

### Option 1
https://user-images.githubusercontent.com/30224372/104824314-77079b00-5805-11eb-8233-a8c1fbcfe176.mp4

### Option 2
https://user-images.githubusercontent.com/30224372/104824317-7a028b80-5805-11eb-8bb7-fbb7f8af72fe.mp4

### CODE REVIEW

**Comment by dvorjackz** [comment]
LOL hmmm maybe try something like this https://www.logostack.com/wp-content/uploads/designers/Manudesign/sad-robot_logoturn2-600x420.png, replace the text with "sold out", greyscale it and make it very light, and take up less space on the page as what you have currently

**Review by dvorjackz — CHANGES_REQUESTED** [review]

**Review by Saagar3690 — COMMENTED** [review]
### **Changes**
Changed the image to the new one @dvorjackz recommended with the recommended filters applied and cleaned up code. Let me know if there's anything I should change to make it more appealing visually. 

### **Images
InventoryModification Screen
IMG_6019

ItemCatalogue Screen
IMG_6018
**

**Review by zhang-edward — APPROVED** [review]
Looks good, I'd say don't worry about the image itself as we can always change it later.

**Review by Saagar3690 — COMMENTED** [review]
Any last thoughts/changes/recommendations?
IMG_6021

**Pull request merged**
