### PR TITLE
Added screen after item creation to prompt and record item weight

### PR DESCRIPTION
**Pull request by Saagar3690**
### **Description**
This is the screen after the add item screen (which Zack is working on). The props for this screen is simply an item id, which will be passed from Zack's screen after he does a POST request. This id prop is necessary to do a PUT request to update the weight for that specific item.
This screen prompts the user to place the item on the scale inside the bot (as guided by the picture*). The user then records the weight measured on the scale by filling out the item weight field and submits. Upon the buttonPressed action event, a PUT request is sent with the data being the id from props and the new local state weight variable using axios. After the request is completed, it alerts the user with success or failure. If request was successful, it will navigate the user back to the add item screen (this is a TODO since this screen has not yet been created).

*Note: The current robot picture is a placeholder for the actual picture, which I envisioned to be a picture of the scale in the bot as to guide the user on where to place the item.

### **Render - iOS**
IMG_5383

### **Render - Android (simulator)**
Screen Shot 2020-11-22 at 9 47 47 PM

### CODE REVIEW

**Review by dvorjackz — CHANGES_REQUESTED** [review]
Don't think it's feasible for the user to be able to see the reading of the scale, nor should we rely on them to enter the weight. Initially, I was thinking of just displaying the reading from the weight on the screen, and once the user sees that it has stabilized, then he can tap the done button to finalize the operation. 

I feel like the following might be better though:
- Get a weight from scale (might open a socket from phone to bot, don't worry about this yet. You can mock this with a function that always returns some constant weight)
- While the weight is constant (so the same item is in the trunk), wait three seconds (during which we can have a loading symbol like [this](https://giphy.com/gifs/mashable-3oEjI6SIIHBdRxXI40))
- App automatically makes the PUT request after that
- Automatically redirect back to the default enterprise screen

**Review by Saagar3690 — COMMENTED** [review]
Made changes as requested. User no longer has to enter the weight since it is not feasible.
Mocked the scale weight measurement in bot by creating a getWeight function that returns a constant value. Item should automatically be detected and will be measured every 1/10 of a second for around 10 seconds, then automatically update weight in the backend. 

There are four main parts to this screen:
1. No item detected, prompts user to place item in bot
2. Shows user that item has been detected and starts measuring weight.
3. Notifies the user weight has been measured, shows measured weight, and indicates it is submitting this data.
4. Shows an alert that weight has been successfully updated (TODO: navigate back to items screen)

IMG_5395
IMG_5396
IMG_5397
IMG_5398

**Review by Saagar3690 — COMMENTED** [review]
Changed loading gif to native react native activity indicator
Made the UI for each stage in the weight measuring process consistent (instead of having re renders and alerts)
IMG_5405
IMG_5406
IMG_5407
IMG_5408

**Review by Saagar3690 — COMMENTED** [review]
Changed base URL and itemId back to original since I forgot to in the previous commits and I was use it for testing the PUT request to backend

**Review by dvorjackz — APPROVED** [review]

**Pull request merged**
